import React from 'react';

function About() {

return (
    <div>
        <h3>Bio</h3>
        <p>LOREN D. THOMAS – OWNER OF F.O.C.U.S., A MINDFULNESS COACH, ONLINE HEALTH, WELLNESS AND FITNESS CONSULTANT. PROFESSIONAL PERSONAL TRAINER, MOTIVATIONAL SPEAKER, PRESENTER AND AUTHOR. FORMER MASTER TRAINER OF THE FIT/STRONG PROGRAM FOR THE UNIVERSITY OF CHICAGO (UIC). MEMBER OF THE SUCCESS IN SPEAKING ACADEMY SPEAKER ROSTER AS A MOTIVATIONAL SPEAKER. OVER 30 YEARS IN THE NURSING AND REHABILITATION FIELD. HE WORKS WITH VARIOUS OF ORGANIZATIONS, CORPORATE OFFICES, COMPANIES, HEALTH CARE VENUES, PRIVATE GROUPS AND INDIVIDUALS WITHIN THE HEALTH, WELLNESS AND FITNESS INDUSTRY.
</p>
    </div>
)

}

export default About